name = "cyber-analyzer-frontend"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.routes]]
pattern = "cyber-analyzer.pages.dev"
custom_domain = true